[Feature] Fixed problem with event handlers and tests
open-format/subgraph pull request #57
Opened 2024-05-29 07:42 UTC by nup9151f

## Summary

This PR fixes problems when running tests using matchstick library and using event handlers.

## Description

Following discussion in OF-129 all global declarations have been moved inside event handlers functions. This allows for the matchstick library to mock the context in tests.

Changes:

- Moved global declarations to event handler functions.
- Added more fixtures that will be used in tests.
- Added some utility functions that will be used in tests.
- Moved existing tests to a `core` folder.

## Related Issue/Bounty

Ref: OF-129  OF-189

## Type of Change

Please check the boxes that apply to your pull request:

- [X ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (changes to documentation only)
- [ ] Code style update (formatting, renaming)
- [X ] Refactoring (no functional changes)
- [ ] Other (please describe):

## Testing

Execute 

```bash
yarn install
yarn run test
```

2024-05-29 08:06 UTC, george-openformat requested changes
great stuff!

I am wondering if `core` is the correct folder. Is this to mirror the the structure in the contracts repo? 

Can we use the same file structure found in `src` in the tests instead?

Couple of tiny things with the fixtures

2024-05-30 04:58 UTC, nup9151f commented
> I am wondering if `core` is the correct folder. Is this to mirror the the structure in the contracts repo?
> Can we use the same file structure found in `src` in the tests instead?

Just did not want to have them right on the tests/ folder, but you are right that is better to have the same structure than `src`

2024-05-30 06:26 UTC, george-openformat approved these changes
Thanks!

2024-05-30 09:29 UTC, tinypell3ts approved these changes

2024-05-31 05:55 UTC, merged