[Feature] Added tests for token functionalities
open-format/subgraph pull request #58
Opened 2024-05-29 07:48 UTC by nup9151f

## Summary

Following #57 Adding more tests for token functionalities.

## Description

Changes:

- Added tests for event handlers in `ERC20Base`, `ERC721Base`, `ERC721LazyMint`

## Related Issue/Bounty

Continuation of #57

2024-05-29 15:57 UTC, george-openformat requested changes
This is looking so good, and fantastic it has caught some bugs.

Mainly just two things
- refactor setting up context into `beforeEach`
- be explicit in the event parameters for each test

2024-05-30 05:13 UTC, nup9151f commented on tests/core/ERC20Base.test.ts
> +        token.save();
We don't need to use `createERC20Token`.
All functionalities in `ERC20Base` just need that the specified token exists in the store. We do not need to create events and trigger handlers to accomplish this, we can create the token directly.
The create erc20 token flow is tested in the facet tests.

2024-05-30 05:55 UTC, nup9151f commented on tests/core/ERC721LazyMint.test.ts
> +        badgeToken.save();
This is the same test than `"Token minted new"` but with a BadgeToken that already exists in the store.
I am not sure whether the badge token already exists when this event handler is triggered.

2024-05-30 06:09 UTC, nup9151f commented on tests/core/ERC20Base.test.ts
> +        transferERC20();
This is an error.
I changed `transferERC20` to receive `from` and `to` as parameters, now burnt supply updates correctly.

2024-05-30 06:34 UTC, george-openformat commented on tests/core/ERC20Base.test.ts
> +        token.save();
Ah interesting thank you for clarifying!

Can't help but feeling that level of coupling for `ERC721` isn't the correct approach but that's an issue for another day!

2024-05-30 07:16 UTC, george-openformat approved these changes
Thanks for those changes and clarifying

If making existing badgeToken owner = null takes more than 5 mins then what you have is perfect.

2024-05-30 07:16 UTC, george-openformat commented on tests/core/ERC721LazyMint.test.ts
> +        badgeToken.save();
Gotcha! I miss interpreted "existing" for `badge` entity and not `badgeToken` entity. This makes total sense when the token has been lazy minted. 

Can the owner be set to `null`?  Looking at the[docs](https://www.assemblyscript.org/types.html#nullability) this is probably more tricky than it is worth.

2024-05-30 09:31 UTC, tinypell3ts approved these changes

2024-05-31 05:39 UTC, nup9151f commented on tests/core/ERC721LazyMint.test.ts
> +        badgeToken.save();
> Can the owner be set to `null`? Looking at the[docs](https://www.assemblyscript.org/types.html#nullability) this is probably more tricky than it is worth.

No problem :+1: 
I also removed `core` folder and moved tests up to mirror `src` folder.

2024-05-31 05:43 UTC, merged