Feature: Added ERC20Point tokens support
open-format/subgraph pull request #75
Opened 2024-12-03 04:23 UTC by nup9151f

## Description

This PR adds support for new ERC20Point contracts. ERC20Points are regular ERC20 tokens with the difference that are non transferable.

New Point tokens are saved as regular `FungibleTokens` with a new attribute indicating that is non transferable.

First Point token to be created for an App is saved as `pointToken` in the App entity, this is similar to current `xpToken` behavior.

New handlers have been created for ERC20Point contract events, current implementartion is the same as ERC20Base handlers but this can change in the future.

**Entity Changes:**

FungibleToken - Added attribute `isNonTransferable` to indicate whether the token is Point type or not. This attribute is always **false** for external token entities.

App - Added attribute `pointToken` that saves first Point token created by the App.

## Type of Change

- [X] New feature (non-breaking change which adds functionality)

## Testing

Tests have been updated.

You may need to execute `yarn clean && yarn prepare:arbitrum-sepolia && yarn gen:arbitrum-sepolia`
 before running tests to generate new schemas and templates.

2024-12-03 16:03 UTC, tinypell3ts approved these changes

2024-12-04 10:02 UTC, george-openformat requested changes
Cheers for this @nup9151f Looking good but I think we need to make the schema changes slightly more future proof.

2024-12-05 01:26 UTC, nup9151f commented on schema.graphql
> +  isNonTransferable: Boolean
That is a good idea :+1:

I created an enum `FungibleTokenType` (possible values: `Point | Base | External`) and replaced `isNonTransferable` with a new `tokenType` attribute.

2024-12-05 01:35 UTC, nup9151f commented on schema.graphql
> +  pointToken: FungibleToken
That makes sense :+1: , attribute `pointToken` has been removed. 

I left the `xpToken` and its corresponding logic untouched, this is still used by the API, until we have better idea how to replace it.

I will remove new endpoint `/v1/reward/point` from API [PR 134](https://github.com/open-format/api/pull/134). We can use the old  `/v1/reward/XP` or `/v1/reward/credit` to reward these Point tokens.

2024-12-05 12:31 UTC, george-openformat commented on schema.graphql
> +  pointToken: FungibleToken
Great thanks @nup9151f 

> I will remove new endpoint /v1/reward/point from API https://github.com/open-format/api/pull/134. We can use the old /v1/reward/XP or /v1/reward/credit to reward these Point tokens.

I see, `reward/point` would still be good to add to the api as overtime we want to remove `xp` ideally in v2 of the api.

2024-12-05 12:32 UTC, george-openformat approved these changes

2024-12-06 03:32 UTC, nup9151f commented on schema.graphql
> +  pointToken: FungibleToken
> I see, `reward/point` would still be good to add to the api as overtime we want to remove `xp` ideally in v2 of the api.

I can reestablish it, that is not a problem.

Just to notice that, given that Point is erc20 token, we will have duplicated functionality between `/reward/credit` and `/reward/point`. Meaning calling `/reward/point` will be the same as calling  `/reward/credit` with parameter `mint: true`. 
Is this the desired outcome?

Before this update the only difference between `reward/point` and `reward/credit` was that we did not pass parameters `mint` and `token_address` to `reward/xp` because we always minted and we got the token address from the `pointToken` in subgraph.

2024-12-06 03:33 UTC, merged